### ISSUE TITLE
Can this algorithm also return the kth shortest path as well?

### ISSUE THREAD

**Issue by das007** [flowlight0/top-k-pruned-landmark-labeling#1]
Hi @flowlight0,

Can this algorithm also return the kth shortest path as well?
I mean it returns the kth shortest distance, but I also want the complete path (which nodes are involved in the path).

**Comment by flowlight0** [comment]
Unfortunately, our method cannot return the kth shortest path because our index doesn't contain enough information to reconstruct it.
